version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/videodb
    depends_on:
      - mongo
    networks:
      - mynetwork

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
